### ISSUE TITLE
Where is the third-party dir?

### ISSUE THREAD

**Issue by yongbin-liu** [ubc-systopia/inconcretes#1]
When I execute the install-libraries-raspbian.sh in scripts/ , it comes "cd: third-party/libconfig: No such file or directory"
How to solve this, thx.

**Comment by Bigone19** [comment]
https://github.com/abseil/abseil-cpp
https://github.com/Tessil/robin-map
https://github.com/Tessil/hopscotch-map
https://github.com/Tessil/array-hash
